version: '2'
services:
  database:
    hostname: database
    image: quay.io/parkervcp/mariadb-alpine:latest
    expose:
      - "3306"
    restart: always
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=apassword"
      - "MYSQL_DATABASE=pterodb"
      - "MYSQL_USER=ptero"
      - "MYSQL_PASSWORD=pterodbpass"
  
  Panel:
    hostname: Panel
    image: quay.io/kasperfranz/pterodactyl-panel:latest
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: always
    links:
      - database
    volumes:
      - "/srv/pterodactyl/var/:/var/www/html/var/"
      - "/srv/pterodactyl/certs/:/root/.caddy/"
    environment:
      - "db_host=database"
      - "db_port=3306"
      - "db_name=pterodb"
      - "db_user=ptero"
      - "db_pass=pterodbpass"
      - "panel_url="
      - "timezone="
      - "email_driver="
      - "panel_email="
      - "email_user="
      - "email_pass="
      - "email_domain="
      - "email_port="
      - "admin_email="
      - "admin_pass="
      - "admin_stat=1"
      - "ssl=true"
      - "driver=memcached"
      - "session_driver=database"
      - "queue_driver=database"
